#!/usr/bin/env bash
# Adding Bash script that displays information about subdomains

if [ "$#" -eq 2 ];
then
	printf "The subdomain %s is a " "$2"
	dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR>1{print $4 " record and points to "$5}'
else
	echo -n "The subdomain www is a "
        dig www."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR>1{print $4 " record and points to "$5}'
	echo -n "The subdomain lb-01 is a "
        dig lb-01."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR>1{print $4 " record and points to "$5}'
	echo -n "The subdomain web-01 is a "
        dig web-01."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR>1{print $4 " record and points to "$5}'
	echo -n "The subdomain web-02 is a "
        dig web-02."$1" | grep -A1 'ANSWER SECTION:' | awk 'NR>1{print $4 " record and points to "$5}'
fi
