#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to honor the above requirements

sudo apt update
sudo apt -y install nginx
sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
