#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to honor the above requirements

sudo apt update
sudo apt install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
