#!/usr/bin/env bash
# Adding a HAproxy setup and configuration on lb-01 server
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install haproxy=2.0.\*

new_string="504.http\n\nfrontend front_server\n\tbind *:80\n\tmode http\n\tdefault_backend back_servers\n\nbackend back_servers\n\tbalance roundrobin\n\toption forwardfor\n\tserver 4466-web-01 54.147.136.182:80 check\n\tserver 4466-web-02 54.163.40.93:80 check\n"

sed -i "s/504.http/$new_string/" /etc/haproxy/haproxy.cfg
service haproxy restart
