#!/usr/bin/env bash
# Adding a HAproxy setup and configuration on lb-01 server
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install haproxy=2.0.\*

new_string="\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 4466-web-01 54.147.136.182:80 check\n\tserver 4466-web-02 54.163.40.93:80 check"

echo -e "$new_string" >> /etc/haproxy/haproxy.cfg

service haproxy restart
