#!/usr/bin/env bash
# Bash script showing the best school 10 times
counter=1

while [ $counter -lt 10 ]
do
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
        echo "Best School"
        ((counter++))
done
