#!/usr/bin/env bash
# Bash script showing the best school 10 times
counter=1

while [ $counter -lt 11 ]
do
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
        ((counter++))
done
