#!/usr/bin/env bash
# Bash script showing best school 10 times but not on 4 and 8
counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"

	elif [ $counter -eq 8 ]
	then
		echo "good luck"

	else
		echo "Best School"
	fi
	((counter++))
done
